# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Usa a imagem oficial de ubuntu da virtualbox
  config.vm.provider "virtualbox" do |vb, override|
    override.vm.box = "ubuntu/xenial64"
    override.vm.synced_folder ".", "/srv/projeto"
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
  end

  # Configura o uso do compartilhamento lxc (contêiner)
  config.vm.provider "lxc" do |_, override|
    override.vm.box = "sputnik13/trusty64"
    override.vm.synced_folder ".", "/srv/projeto", :type => "nfs"
  end

  # Configura o uso do compartilhamento libvir (virtualização)
  config.vm.provider "libvirt" do |_, override|
    override.vm.box = "sputnik13/trusty64"
    override.vm.synced_folder ".", "/srv/projeto", :type => "nfs"
  end

  # Configura a cache de programas compartilhados se possível
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.enable :apt
    config.cache.scope = :box
  end

  # Redirecionamento de porta (port forward) para o servidor e banco de dados
  config.vm.network :forwarded_port, :guest => 3000, :host => 3000
  config.vm.network :forwarded_port, :guest => 5432, :host => 5433

  # Manda executar o script para instalar programas (provision)
  config.vm.provision :shell, :path => "script/vagrant/setup/provision.sh"
end
